export const NAV_ITEMS = [
    { href: "/", label: "Dashboard" },
    { href: "/watchlist", label: "Watchlist" },
];

export interface StockListing {
    symbol: string;
    name: string;
    exchange: string;
}

// Curated list of widely traded stocks used for client-side search.
export const POPULAR_STOCKS: StockListing[] = [
    { symbol: "AAPL", name: "Apple Inc.", exchange: "NASDAQ" },
    { symbol: "MSFT", name: "Microsoft Corporation", exchange: "NASDAQ" },
    { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", exchange: "NASDAQ" },
    { symbol: "AMZN", name: "Amazon.com Inc.", exchange: "NASDAQ" },
    { symbol: "NVDA", name: "NVIDIA Corporation", exchange: "NASDAQ" },
    { symbol: "META", name: "Meta Platforms Inc.", exchange: "NASDAQ" },
    { symbol: "TSLA", name: "Tesla Inc.", exchange: "NASDAQ" },
    { symbol: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)", exchange: "NYSE" },
    { symbol: "JPM", name: "JPMorgan Chase & Co.", exchange: "NYSE" },
    { symbol: "V", name: "Visa Inc.", exchange: "NYSE" },
    { symbol: "MA", name: "Mastercard Incorporated", exchange: "NYSE" },
    { symbol: "UNH", name: "UnitedHealth Group Incorporated", exchange: "NYSE" },
    { symbol: "JNJ", name: "Johnson & Johnson", exchange: "NYSE" },
    { symbol: "WMT", name: "Walmart Inc.", exchange: "NYSE" },
    { symbol: "PG", name: "Procter & Gamble Company", exchange: "NYSE" },
    { symbol: "XOM", name: "Exxon Mobil Corporation", exchange: "NYSE" },
    { symbol: "CVX", name: "Chevron Corporation", exchange: "NYSE" },
    { symbol: "HD", name: "Home Depot Inc.", exchange: "NYSE" },
    { symbol: "KO", name: "Coca-Cola Company", exchange: "NYSE" },
    { symbol: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ" },
    { symbol: "COST", name: "Costco Wholesale Corporation", exchange: "NASDAQ" },
    { symbol: "MCD", name: "McDonald's Corporation", exchange: "NYSE" },
    { symbol: "DIS", name: "Walt Disney Company", exchange: "NYSE" },
    { symbol: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ" },
    { symbol: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ" },
    { symbol: "CRM", name: "Salesforce Inc.", exchange: "NYSE" },
    { symbol: "ORCL", name: "Oracle Corporation", exchange: "NYSE" },
    { symbol: "INTC", name: "Intel Corporation", exchange: "NASDAQ" },
    { symbol: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ" },
    { symbol: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ" },
    { symbol: "QCOM", name: "QUALCOMM Incorporated", exchange: "NASDAQ" },
    { symbol: "TXN", name: "Texas Instruments Incorporated", exchange: "NASDAQ" },
    { symbol: "IBM", name: "International Business Machines", exchange: "NYSE" },
    { symbol: "CSCO", name: "Cisco Systems Inc.", exchange: "NASDAQ" },
    { symbol: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ" },
    { symbol: "SQ", name: "Block Inc.", exchange: "NYSE" },
    { symbol: "SHOP", name: "Shopify Inc.", exchange: "NYSE" },
    { symbol: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE" },
    { symbol: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ" },
    { symbol: "SNOW", name: "Snowflake Inc.", exchange: "NYSE" },
    { symbol: "PLTR", name: "Palantir Technologies Inc.", exchange: "NASDAQ" },
    { symbol: "COIN", name: "Coinbase Global Inc.", exchange: "NASDAQ" },
    { symbol: "BA", name: "Boeing Company", exchange: "NYSE" },
    { symbol: "CAT", name: "Caterpillar Inc.", exchange: "NYSE" },
    { symbol: "GE", name: "General Electric Company", exchange: "NYSE" },
    { symbol: "F", name: "Ford Motor Company", exchange: "NYSE" },
    { symbol: "GM", name: "General Motors Company", exchange: "NYSE" },
    { symbol: "NKE", name: "Nike Inc.", exchange: "NYSE" },
    { symbol: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ" },
    { symbol: "T", name: "AT&T Inc.", exchange: "NYSE" },
    { symbol: "VZ", name: "Verizon Communications Inc.", exchange: "NYSE" },
    { symbol: "PFE", name: "Pfizer Inc.", exchange: "NYSE" },
    { symbol: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE" },
    { symbol: "ABBV", name: "AbbVie Inc.", exchange: "NYSE" },
    { symbol: "LLY", name: "Eli Lilly and Company", exchange: "NYSE" },
    { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", exchange: "NYSE" },
    { symbol: "GS", name: "Goldman Sachs Group Inc.", exchange: "NYSE" },
    { symbol: "MS", name: "Morgan Stanley", exchange: "NYSE" },
    { symbol: "BAC", name: "Bank of America Corporation", exchange: "NYSE" },
    { symbol: "WFC", name: "Wells Fargo & Company", exchange: "NYSE" },
    { symbol: "C", name: "Citigroup Inc.", exchange: "NYSE" },
    { symbol: "SPOT", name: "Spotify Technology S.A.", exchange: "NYSE" },
    { symbol: "RDDT", name: "Reddit Inc.", exchange: "NYSE" },
    { symbol: "ARM", name: "Arm Holdings plc", exchange: "NASDAQ" },
    { symbol: "SMCI", name: "Super Micro Computer Inc.", exchange: "NASDAQ" },
    { symbol: "MU", name: "Micron Technology Inc.", exchange: "NASDAQ" },
    { symbol: "LRCX", name: "Lam Research Corporation", exchange: "NASDAQ" },
    { symbol: "AMAT", name: "Applied Materials Inc.", exchange: "NASDAQ" },
    { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing", exchange: "NYSE" },
    { symbol: "ASML", name: "ASML Holding N.V.", exchange: "NASDAQ" },
    { symbol: "LIN", name: "Linde plc", exchange: "NASDAQ" },
    { symbol: "RTX", name: "RTX Corporation", exchange: "NYSE" },
    { symbol: "HON", name: "Honeywell International Inc.", exchange: "NASDAQ" },
    { symbol: "UPS", name: "United Parcel Service Inc.", exchange: "NYSE" },
    { symbol: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE" },
    { symbol: "INTU", name: "Intuit Inc.", exchange: "NASDAQ" },
    { symbol: "NOW", name: "ServiceNow Inc.", exchange: "NYSE" },
    { symbol: "PANW", name: "Palo Alto Networks Inc.", exchange: "NASDAQ" },
    { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "NASDAQ" },
    { symbol: "NET", name: "Cloudflare Inc.", exchange: "NYSE" },
    { symbol: "DDOG", name: "Datadog Inc.", exchange: "NASDAQ" },
    { symbol: "MDB", name: "MongoDB Inc.", exchange: "NASDAQ" },
];

export function findStock(symbol: string): StockListing | undefined {
    return POPULAR_STOCKS.find(
        (s) => s.symbol.toUpperCase() === symbol.toUpperCase()
    );
}
